base_images:
  ansible:
    name: "4.9"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.9"
    namespace: ocp
    tag: cli
  ocp_builder_rhel-8-golang-1.16-openshift-4.9:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.16-openshift-4.9
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.9"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.9"
  tools:
    name: "4.9"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.9"
    namespace: ocp
    tag: upi-installer
binary_build_commands: make all
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
releases:
  latest:
    prerelease:
      product: ocp
      version_bounds:
        lower: 4.9.0
        upper: 4.10.0-0
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
test_binary_build_commands: make test
tests:
- as: e2e-vsphere-upi
  cron: 0 12 */7 * *
  steps:
    cluster_profile: vsphere
    env:
      E2E_RUN_TAGS: '@vsphere-upi and @network-openshiftsdn and not @fips'
      TAG_VERSION: '@4.9'
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-vsphere-upi
zz_generated_metadata:
  branch: release-4.9
  org: openshift
  repo: openshift-tests-private
  variant: amd64-stable
